
train:
    _target_: torch.utils.data.DataLoader
    pin_memory: True
    drop_last: True
    shuffle: False
    num_workers: 8
    persistent_workers: True
    batch_size: 18

val:
    _target_: torch.utils.data.DataLoader
    pin_memory: True
    drop_last: False
    shuffle: False
    batch_size: 32
    num_workers: 2
    